# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

# This will create a Flink image with extra files.
# It will be used to include the Hadoop libraries.

# Replace FROM line with your own Docker repository.
FROM devops-repo.isus.emc.com:8116/nautilus/flink:1.10.0-2.12-1.2-W2-4-0577915d2

COPY files/ /
